---
- name: Install required packages
  ansible.builtin.apt:
    name: auditd
    state: present

- name: Enable auditd service
  ansible.builtin.service:
    name: auditd
    state: started
    enabled: true

- name: Configure audit rules
  ansible.builtin.copy:
    src: auditd/audit.rules
    dest: /etc/audit/rules.d/audit.rules
    owner: root
    group: root
    mode: '0600'
  notify: Restart auditd
