---
- name: Install required packages
  apt:
    name:
      - fail2ban
      - rsyslog
    state: present

- name: Ensure required services are started and enabled
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop:
    - fail2ban
    - rsyslog

- name: Copy jail.local configuration
  copy:
    src: fail2ban/jail.local
    dest: /etc/fail2ban/jail.local
    owner: root
    group: root
    mode: '0644'

- name: Validate fail2ban configuration
  command: fail2ban-client -t
  changed_when: false
  notify: Restart fail2ban
