---
- name: Install rkhunter
  apt:
    name: rkhunter
    state: present

- name: Create rkhunter scripts directory
  file:
    path: /etc/rkhunter.d
    state: directory
    mode: '0755'

- name: Configure Docker whitelist for rkhunter
  copy:
    dest: /etc/rkhunter.d/docker.conf
    content: |
      # Whitelist Docker
      ALLOWHIDDENDIR=/var/lib/docker
      ALLOWHIDDENDIR=/var/lib/docker/overlay2
      ALLOWHIDDENDIR=/run/docker
      ALLOWDEVFILE=/var/run/docker.sock
      ALLOWPROCLISTEN=/usr/bin/dockerd

- name: Configure rkhunter main settings
  copy:
    dest: /etc/rkhunter.d/main.conf
    content: |
      # Main configuration
      UPDATE_MIRRORS=0
      WEB_CMD=""
      MIRRORS_MODE=1
      USE_SYSLOG=authpriv.warning
      TMPDIR=/var/lib/rkhunter/tmp
      DBDIR=/var/lib/rkhunter/db
      SCRIPTDIR=/usr/share/rkhunter/scripts
      DISABLE_TESTS=suspscan hidden_ports hidden_procs deleted_files packet_cap_apps apps
  notify: Run rkhunter update

- name: Setup daily rkhunter check
  copy:
    dest: /etc/cron.daily/rkhunter
    content: |
      #!/bin/sh
      /usr/bin/rkhunter --cronjob --quiet
    mode: '0755'
