---
- name: Install openssh-server
  ansible.builtin.apt:
    name: openssh-server
    state: present

- name: Ensure .ssh directory exists
  ansible.builtin.file:
    path: "/home/{{ item.username }}/.ssh"
    state: directory
    owner: "{{ item.username }}"
    group: "{{ item.username }}"
    mode: '0700'
  loop: "{{ global_config.users }}"

- name: Add authorized SSH keys
  authorized_key:
    user: "{{ item.username }}"
    key: "{{ item.ssh_keys | join('\n') }}"
    state: present
  loop: "{{ global_config.users }}"
  when: item.ssh_keys is defined and item.ssh_keys | length > 0

- name: Copy SSH configuration
  ansible.builtin.copy:
    src: sshd/sshd_config
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: '0600'
    validate: '/usr/sbin/sshd -t -f %s'
  notify: Reloaded SSH
