# Set up the prompt
autoload -Uz promptinit
promptinit
PROMPT='%F{green}%n@%m%f:%F{blue}%~%f$ '

setopt histignorealldups sharehistory
setopt EXTENDED_HISTORY          # Ajoute le timestamp à l'historique
setopt HIST_EXPIRE_DUPS_FIRST   # Supprime les duplicatas en premier
setopt HIST_IGNORE_SPACE        # Ignore les commandes commençant par un espace
setopt HIST_VERIFY              # Affiche la commande avant de l'exécuter depuis l'historique

setopt AUTO_CD                  # Permet de taper le nom d'un dossier pour s'y rendre
setopt CORRECT                  # Correction automatique des commandes
setopt INTERACTIVE_COMMENTS     # Permet les commentaires dans les commandes interactives

# Use emacs keybindings even if our EDITOR is set to vi
bindkey -e

# Keep 10000 lines of history within the shell and save it to ~/.zsh_history:
export HISTSIZE=10000
export HISTFILESIZE=10000
export HISTTIMEFORMAT="%F %T "
HISTFILE=~/.zsh_history

# Aliases
alias ll='ls -lah'
alias la='ls -A'
alias l='ls -CF'
alias gg='ping 8.8.8.8'

alias cd..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'

alias c='clear'
alias h='history'
alias maj='sudo apt update && sudo apt upgrade'
alias ports='netstat -tulanp'
alias mem='free -h'
alias df='df -h'

alias gs='git status'
alias ga='git add'
alias gc='git commit -m'
alias gp='git push'
alias gl='git pull'

# Use modern completion system
autoload -Uz compinit
compinit

zstyle ':completion:*' auto-description 'specify: %d'
zstyle ':completion:*' completer _expand _complete _correct _approximate
zstyle ':completion:*' format 'Completing %d'
zstyle ':completion:*' group-name ''
zstyle ':completion:*' menu select=2
eval "$(dircolors -b)"
zstyle ':completion:*:default' list-colors ${(s.:.)LS_COLORS}
zstyle ':completion:*' list-colors ''
zstyle ':completion:*' list-prompt %SAt %p: Hit TAB for more, or the character to insert%s
zstyle ':completion:*' menu select=long
zstyle ':completion:*' select-prompt %SScrolling active: current selection at %p%s
zstyle ':completion:*' use-compctl false
zstyle ':completion:*' verbose true
zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}' 'r:|[._-]=* r:|=*' 'l:|=* r:|=*'
zstyle ':completion:*' special-dirs true
zstyle ':completion:*:*:kill:*:processes' list-colors '=(#b) #([0-9]#)*=0=01;31'
zstyle ':completion:*:kill:*' command 'ps -u $USER -o pid,%cpu,tty,cputime,cmd'