---
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600

- name: Install system packages
  ansible.builtin.apt:
    name: "{{ common_packages.system }}"
    state: present

- name: Install monitoring packages
  ansible.builtin.apt:
    name: "{{ common_packages.monitoring }}"
    state: present

- name: Install security packages
  ansible.builtin.apt:
    name: "{{ common_packages.security }}"
    state: present
