---
- name: Set timezone
  timezone:
    name: "{{ global_config.timezone }}"

- name: Generate required locales
  locale_gen:
    name: "{{ global_config.locale }}"
    state: present

- name: Configure sysctl parameters
  sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    state: present
    reload: true
  with_dict: "{{ common_config.sysctl }}"
