---
- name: Set up sudo config
  ansible.builtin.copy:
    dest: /etc/sudoers.d/admin
    content: |
      %sudo ALL=(ALL) NOPASSWD: ALL
    mode: '0440'
    validate: '/usr/sbin/visudo -cf %s'

- name: Create users
  ansible.builtin.user:
    name: "{{ item.username }}"
    groups: "{{ item.groups | default([]) }}"
    shell: "{{ item.shell | default('/bin/bash') }}"
    append: true
    state: present
  loop: "{{ global_config.users }}"

- name: Ensure user home directories exist
  ansible.builtin.file:
    path: "/home/{{ item.username }}"
    state: directory
    mode: '0750'
    owner: "{{ item.username }}"
    group: "{{ item.username }}"
  loop: "{{ global_config.users }}"

- name: Create bashrc for users
  ansible.builtin.copy:
    src: zshrc
    dest: "/home/{{ item.username }}/.zshrc"
    mode: '0644'
    owner: "{{ item.username }}"
    group: "{{ item.username }}"
  loop: "{{ global_config.users }}"
