---
- name: Configure Debian 12 server
  hosts: debian_servers
  become: true
  become_method: ansible.builtin.su
  become_user: root
  become_flags: "-"
  roles:
    - role: common
      tags: ['common', 'system']
    - role: docker
      tags: ['docker', 'containers']
    - role: security
      tags: ['security', 'hardening']
