---
- name: Reloaded SSH
  ansible.builtin.service:
    name: "{{ ssh_service_name[ansible_distribution] }}"
    state: reloaded

- name: Restart fail2ban
  ansible.builtin.service:
    name: fail2ban
    state: restarted

- name: Restart auditd
  ansible.builtin.service:
    name: auditd
    state: restarted

- name: Restart Logrotate
  ansible.builtin.service:
    name: logrotate
    state: restarted
